# Use the official MariaDB image as a base
FROM mariadb:10.11

# Set environment variables for the database
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=microservicesdb
ENV MYSQL_USER=mysqluser
ENV MYSQL_PASSWORD=password

# Expose the default MariaDB port
EXPOSE 3306