# Use the official PostgreSQL image as the base
FROM postgres:16

# Set environment variables for the database
ENV POSTGRES_DB=microservicesdb
ENV POSTGRES_USER=postgresuser
ENV POSTGRES_PASSWORD=password

# Expose the default PostgreSQL port
EXPOSE 5432