package oldlogger

const (
	LOG_TO_CONSOLE_JSON     = "LOG_TO_CONSOLE_JSON"
	LOG_TO_CONSOLE_TEXT     = "LOG_TO_CONSOLE_TEXT"
	LOG_TO_CONSOLE_DIRECT   = "LOG_TO_CONSOLE_DIRECT"
	LOG_TO_LOGSTASH         = "LOG_TO_LOGSTASH"
	DEFAULT_LOG_DESTINATION = "LOG_TO_LOGSTASH"
	DEFAULT_LOG_LEVEL       = "Info"
)
